[package]
name = "runtime"
version = "1.0.2"
authors = [ "Microsoft Corporation" ]
description = "Demikernel's Runtime"
homepage = "https://aka.ms/demikernel"
repository = "https://github.com/demikernel/catnip"
readme = "README.md"
license-file = "LICENSE"
edition = "2018"

[dependencies]
arrayvec = "0.7.2"
derive_more = "0.99.17"
eui48 = "1.1.0"
float_duration = "0.3.3"
flexi_logger = "0.22.3"
futures = "0.3.21"
libc = "0.2.115"
log = "0.4.14"
slab = "0.4.5"
rand = { version = "0.8.4", features = ["small_rng"] }

scheduler = { git = "https://github.com/demikernel/scheduler", rev = "7bd71378a6121e33bf55f79248f2a2a812815d6e" }

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
rpath = false
