[package]
name = "runtime"
version = "1.1.3"
authors = [ "Microsoft Corporation" ]
description = "Demikernel's Runtime"
homepage = "https://aka.ms/demikernel"
repository = "https://github.com/demikernel/runtime"
readme = "README.md"
license-file = "LICENSE"
edition = "2018"

[dependencies]
arrayvec = "0.7.2"
derive_more = "0.99.17"
eui48 = "1.1.0"
float_duration = "0.3.3"
flexi_logger = "0.22.5"
futures = "0.3.21"
libc = "0.2.126"
log = "0.4.17"
slab = "0.4.6"

scheduler = { git = "https://github.com/demikernel/scheduler", rev = "820716f1d28411bc505396a64f4815052670f9d7" }
liburing = { git = "https://github.com/demikernel/liburing-rs", rev = "52d86b1133dc4b1202563ac24e418fa2fd606067", optional = true}
dpdk-rs = { git = "https://github.com/demikernel/dpdk-rs", rev = "17e7a4d820a60c94c0739739cc06bb8483771ea4", optional = true }
perftools = { git = "https://github.com/demikernel/perftools", rev = "077c7eec3797dc9531559520e3f6cbdfe6f5daf4", optional = true}

[features]
default = [ ]
libdpdk = [ "dpdk-rs" ]
mlx4 = [ "dpdk-rs/mlx4" ]
mlx5 = [ "dpdk-rs/mlx5" ]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
rpath = false
