[package]
name = "runtime"
version = "1.0.3"
authors = [ "Microsoft Corporation" ]
description = "Demikernel's Runtime"
homepage = "https://aka.ms/demikernel"
repository = "https://github.com/demikernel/runtime"
readme = "README.md"
license-file = "LICENSE"
edition = "2018"

[dependencies]
arrayvec = "0.7.2"
derive_more = "0.99.17"
eui48 = "1.1.0"
float_duration = "0.3.3"
flexi_logger = "0.22.3"
futures = "0.3.21"
libc = "0.2.125"
log = "0.4.17"
slab = "0.4.6"
rand = { version = "0.8.5", features = ["small_rng"] }

scheduler = { git = "https://github.com/demikernel/scheduler", rev = "7bd71378a6121e33bf55f79248f2a2a812815d6e" }
liburing = { git = "https://github.com/demikernel/liburing-rs", rev = "99a28909284bf5b9e23dd8df4c61b35c8731e217", optional = true}
dpdk-rs = { git = "https://github.com/demikernel/dpdk-rs", rev = "f6619d5313fc224e6bf8620df7485517efea0e39", optional = true }

[features]
default = [ ]
libdpdk = [ "dpdk-rs" ]
mlx4 = [ "dpdk-rs/mlx4" ]
mlx5 = [ "dpdk-rs/mlx5" ]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
rpath = false
